version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    ports:
      - "3306:3306"
  nginx:
    build: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/var/www/code
  fpm:
    build: ./docker/fpm/
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/code